### ISSUE TITLE
OpenAPI docs are rotten

### ISSUE THREAD

**Issue by raimohanska** [raimohanska/ourboard#196]
For quite a while the API docs haven't been updated at all.

- When you run `yarn apidocs` nothing happens. The file `backend/src/api/api-routes.openapi.ts` remains unchanged.
- The operation has probably been a no-op since `api-routes.ts` was moved. 
- It's probably a bug in `typera-openapi` that this fails silently
- When I point the apidocs task in `backend/package.json` to point to the right file, I get a really nasty error:

```
$ cd backend && yarn apidocs
$ typera-openapi --prettify src/api/api-routes.ts
/Users/juha/code/ourboard/node_modules/typera-openapi/node_modules/typescript/lib/typescript.js:27102
        return node.kind === 249 /* VariableDeclaration */;
                    ^

TypeError: Cannot read property 'kind' of undefined
    at Object.isVariableDeclaration (/Users/juha/code/ourboard/node_modules/typera-openapi/node_modules/typescript/lib/typescript.js:27102:21)
    at getRouteInput (/Users/juha/code/ourboard/node_modules/typera-openapi/dist/generate.js:130:13)
    at getRouteDeclaration (/Users/juha/code/ourboard/node_modules/typera-openapi/dist/generate.js:72:24)
    at /Users/juha/code/ourboard/node_modules/typera-openapi/dist/generate.js:37:38
    at Array.forEach (<anonymous>)
    at visit (/Users/juha/code/ourboard/node_modules/typera-openapi/dist/generate.js:35:20)
    at /Users/juha/code/ourboard/node_modules/typera-openapi/dist/generate.js:19:27
    at visitNodes (/Users/juha/code/ourboard/node_modules/typera-openapi/node_modules/typescript/lib/typescript.js:28217:30)
    at Object.forEachChild (/Users/juha/code/ourboard/node_modules/typera-openapi/node_modules/typescript/lib/typescript.js:28456:24)
    at Object.generate (/Users/juha/code/ourboard/node_modules/typera-openapi/dist/generate.js:18:12)

```

**Comment by raimohanska** [comment]
Removed for now
