### ISSUE TITLE
The exception occurred in the latest code.

### ISSUE THREAD

**Issue by mnmfjt** [raimohanska/ourboard#204]
# Feature request story or issue
Hi there.
I am trying to run locally.
Please let me know if there are any errors in my procedure.

## Screenshot

I found the exception in the console, so paste the log after typing " yarn dev".
```
ubuntu@******************:~/ourboard$ yarn dev
yarn run v1.22.19
$ npm-run-all --parallel dev:db watch:frontend dev:backend typecheck:dev:frontend
$ yarn --cwd backend dev
$ yarn --cwd frontend watch
$ docker-compose up||true
$ cd frontend && tsc --noEmit --preserveWatchOutput --watch
$ npm-run-all --parallel watch apidocs:dev
$ node esbuild.js watch
[7:29:47 AM] Starting compilation in watch mode...

Starting ourboard_db_1 ...
$ nodemon --watch src/api-routes.ts --exec 'yarn apidocs'
Starting ourboard_db_1 ... done
Attaching to ourboard_db_1
db_1  |
db_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
db_1  |
db_1  | 2023-02-15 07:29:49.381 UTC [1] LOG:  starting PostgreSQL 12.13 (Debian 12.13-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
db_1  | 2023-02-15 07:29:49.381 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1  | 2023-02-15 07:29:49.381 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1  | 2023-02-15 07:29:49.385 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db_1  | 2023-02-15 07:29:49.410 UTC [27] LOG:  database system was shut down at 2023-02-15 06:07:52 UTC
db_1  | 2023-02-15 07:29:49.416 UTC [1] LOG:  database system is ready to accept connections
[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): src/api-routes.ts
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `yarn apidocs`

7:29:50 AM - Starting compilation in watch mode...

Frontend build done, took 2024 ms
$ typera-openapi --prettify src/api-routes.ts
[nodemon] clean exit - waiting for changes before restart
[7:30:15 AM] Found 0 errors. Watching for file changes.


7:30:32 AM - Found 0 errors. Watching for file changes.
/home/ubuntu/ourboard/backend/src/env.ts:5
    if (!value) throw new Error("Missing ENV: " + name)
                      ^

Error: Missing ENV: SESSION_SIGNING_SECRET
    at Object.getEnv (/home/ubuntu/ourboard/backend/src/env.ts:5:23)
    at Object.<anonymous> (/home/ubuntu/ourboard/backend/src/http-session.ts:7:16)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:16)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/ubuntu/ourboard/backend/src/common-event-handler.ts:5:1)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
```
## Url

-   Url where you took the screenshot:
-   URL: I am sorry but I have found in my self host.

## A sentence description of the problem

Short DESCRIPTION:
The exception occurred in the latest code.

### Environment:
- OS:Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-1028-awｌs x86_64)
- Node:v15.14.0
- Docker:v23.0.0
- Docker-compose:1.29.0
- yarn:1.22.19

### My Operation:
1. git clone https://github.com/raimohanska/ourboard
2. yarn install
3. yarn dev

**Comment by raimohanska** [comment]
Looks like the environment variable SESSION_SIGNING_SECRET is missing. Add this to backend/.env file. There may be other undocumented requirements. Let's document them after you've found them :)

**Comment by mnmfjt** [comment]
Thank you so much for your quick reply!
I tried it exactly as you told me and it worked!
Actually I added three more parameters though :)
These are the parameters I added.
```
GOOGLE_OAUTH_CLIENT_ID
GOOGLE_OAUTH_CLIENT_SECRET
ROOT_URL
```
